# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - 'release'

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Trigger storage example with latest 0xweb
        env:
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
        run: |
          curl -X POST https://circleci.com/api/v2/project/github/0xweb-org/examples-storage/pipeline \
               -H "Circle-Token: $CIRCLECI_TOKEN" \
               -H "Content-Type: application/json" \
               -d '{ "branch": "master" }'
      - name: Trigger backend example with latest 0xweb
        env:
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
        run: |
          curl -X POST https://circleci.com/api/v2/project/github/0xweb-org/examples-backend/pipeline \
               -H "Circle-Token: $CIRCLECI_TOKEN" \
               -H "Content-Type: application/json" \
               -d '{ "branch": "master" }'

      - name: Trigger hardhat example with latest 0xweb
        env:
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
        run: |
          curl -X POST https://circleci.com/api/v2/project/github/0xweb-org/examples-hardhat/pipeline \
               -H "Circle-Token: $CIRCLECI_TOKEN" \
               -H "Content-Type: application/json" \
               -d '{ "branch": "master" }'

      - name: Trigger hardhat example with latest 0xweb
        env:
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
        run: |
          curl -X POST https://circleci.com/api/v2/project/github/0xweb-org/examples-price/pipeline \
               -H "Circle-Token: $CIRCLECI_TOKEN" \
               -H "Content-Type: application/json" \
               -d '{ "branch": "master" }'
